#!/usr/bin/env bash

function run {
  if ! pgrep -f "$1" ;
  then
    $@&
  fi
}

run "picom"
#$HOME/.local/bin/tint2start.sh &
run "$HOME/.screenlayout/default.sh"
run "$HOME/.fehbg"
run "redshift-gtk -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')"
run "lxpolkit"
